name: Go CI

on:
  push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Go Format
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: './src'
          gofmt-flags: '-l -d'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: test
        run: go test -v ./pkg


